src/components/Footer/Container.jsx
src/components/Logos/Logos.jsx

- Change sponsor heading colour and footer band colour to the appropriate colours in the design specification.

fix: sponsor heading colour and footer band colour to design spec.

---

src/components/DocPages/CodeofConduct.jsx

Fix: new co-directors contact info

---

src/components/FAQ/FAQ.jsx

- Changes the dates from *January 29-31* to *January 21-23* in the FAQ
- If the change is correct, fixes #10

Change McHacks dates in FAQ

---

src/components/Logos/Logos.jsx

- HCK-
- Fix link for Front Row Ventures

Fix logo link

---

src/components/Logos/Logos.jsx

- HCK-
- Update Secureworks link

Update Secureworks link

---

src/components/Discord/Text.jsx
src/components/FAQ/Container.jsx
src/components/Live/Info.jsx
src/components/Live/LiveContainer.jsx
src/components/Live/LiveNav.jsx
src/components/Live/Resources.jsx
src/components/Schedule/Container.jsx

- HCK-
- Fix nav
- Fix resources page
- Update styling

Update styling for live site

---

src/components/Discord/Text.jsx
src/components/FAQ/Container.jsx
src/components/Live/Info.jsx
src/components/Live/LiveContainer.jsx
src/components/Live/LiveNav.jsx
src/components/Live/Resources.jsx
src/components/Logos/Logos.jsx
src/components/Nav/NavLink.jsx
src/components/Schedule/Container.jsx

Fix styling

---

src/components/Logos/Logos.jsx

- HCK-
- Fix sponsors logo sizing

fix sponsors logos

---

src/components/Schedule/Container.jsx
src/components/Schedule/Event.jsx
src/components/Schedule/events.jsx

- HCK-
- added event schedule to the live site

feat: added events

---

src/components/Schedule/Container.jsx
src/components/Schedule/Event.jsx
src/components/Schedule/events.jsx

chore: merge dev into main.

---

src/components/Schedule/events.jsx

- HCK-
- added MLH event and Typing Races

feat: added MLH event and Typing Races

---

src/components/Live/Resources.jsx

Add sponsor api

---

src/components/Logos/Logos.jsx

Add sponsor api into main

---

src/components/Live/Resources.jsx
src/components/Logos/Logos.jsx
src/components/Schedule/Container.jsx
src/components/Schedule/Event.jsx
src/components/Schedule/events.jsx

Added sponsorship schedule into main

---

src/components/Schedule/events.jsx

- HCK-
- added main event schedule

feat: added main event schedule

---

src/components/Schedule/events.jsx

Fix hacking start time typo

---

src/components/Schedule/events.jsx

updated schedule sponsors, closing ceremonie time and design

---

src/components/Schedule/events.jsx

feat: RailVision workshop

---

src/components/Schedule/events.jsx

feat: RailVision workshop to main

---

src/components/Live/Resources.jsx

update ovh code

---

src/components/Schedule/Schedule.jsx

chore: change schedule to Sunday

---

src/components/Schedule/Schedule.jsx

chore: change schedule to Sunday to main
